In [1]:
import torch

/Users/zhongmuyao/opt/miniconda3/envs/py310/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
from Ptr_EA import PEncoder as PE

In [4]:
pe=PE(128,64,1,0,False)

In [5]:
ps=pe.parameters()

In [6]:
ps

<generator object Module.parameters at 0x12e305af0>

In [7]:
for p in ps:
    print(p)

Parameter containing:
tensor([0.])
Parameter containing:
tensor([0.])
Parameter containing:
tensor([[ 0.1092, -0.0337,  0.0366,  ...,  0.0925, -0.1119,  0.1025],
        [ 0.0688,  0.0289, -0.1199,  ..., -0.0329,  0.0893,  0.0364],
        [ 0.0051,  0.1177, -0.0414,  ..., -0.0749,  0.0210,  0.0480],
        ...,
        [ 0.0754, -0.0064, -0.0844,  ..., -0.0425, -0.0853, -0.0427],
        [ 0.0128,  0.0482, -0.0567,  ...,  0.0225, -0.0900,  0.0064],
        [-0.0778, -0.0990,  0.0670,  ...,  0.0637,  0.0458, -0.0582]],
       requires_grad=True)
Parameter containing:
tensor([[-0.0226,  0.0237, -0.0669,  ...,  0.0782, -0.0119, -0.0683],
        [-0.0195, -0.0562,  0.0411,  ..., -0.0113,  0.1109,  0.0577],
        [ 0.0206, -0.0570, -0.0446,  ...,  0.0862, -0.1159, -0.0127],
        ...,
        [-0.0049, -0.0401,  0.0017,  ...,  0.1078,  0.0296, -0.0948],
        [-0.1138,  0.0314,  0.0133,  ...,  0.0324,  0.1192, -0.1150],
        [ 0.0510,  0.0296,  0.0752,  ..., -0.1125,  0.0644, -0

In [10]:
ps=pe.parameters()
for p in ps:
    print(p.shape)

torch.Size([1])
torch.Size([1])
torch.Size([256, 128])
torch.Size([256, 64])
torch.Size([256])
torch.Size([256])


In [11]:
pe.weight_ih_l[0]

AttributeError: 'PEncoder' object has no attribute 'weight_ih_l'

In [12]:
l=pe.lstm

In [14]:
l.weight_ih_l0.shape

torch.Size([256, 128])

In [16]:
l.weight_hh_l0.values=torch.ones((256,128))

In [17]:
l.weight_hh_l0

Parameter containing:
tensor([[-0.0226,  0.0237, -0.0669,  ...,  0.0782, -0.0119, -0.0683],
        [-0.0195, -0.0562,  0.0411,  ..., -0.0113,  0.1109,  0.0577],
        [ 0.0206, -0.0570, -0.0446,  ...,  0.0862, -0.1159, -0.0127],
        ...,
        [-0.0049, -0.0401,  0.0017,  ...,  0.1078,  0.0296, -0.0948],
        [-0.1138,  0.0314,  0.0133,  ...,  0.0324,  0.1192, -0.1150],
        [ 0.0510,  0.0296,  0.0752,  ..., -0.1125,  0.0644, -0.0487]],
       requires_grad=True)

In [20]:
xx=torch.ones((256,128))

In [21]:
xx.shape

torch.Size([256, 128])

In [22]:
l.weight_hh_l0.copy_(torch.ones((256,128)))

RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.

In [23]:
pe.train(False)

PEncoder(
  (lstm): LSTM(128, 64)
)

In [24]:
ps=pe.parameters()

In [25]:
l=pe.lstm

In [26]:
l.weight_hh_l0.copy_(torch.zeros(256,128))

RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.

In [27]:
from torch.nn import Parameter


In [28]:
rep=Parameter(torch.zeros((256,128)),requires_grad=True)

In [29]:
l.weight_hh_l0.copy_(rep)

RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.

In [30]:
l.weight_hh_l0.data=rep 

In [31]:
l.weight_hh_l0

Parameter containing:
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], requires_grad=True)

In [32]:
l.weight_hh_l0.values

tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]])

In [33]:
l.weight_hh_l0.data+=1

In [34]:
l.weight_hh_l0.data

tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]])

In [35]:
l.weight_hh_l0.values

tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]])