In [1]:
import torch
import torch.nn as nn 
from torch.nn import Parameter
import torch.nn.functional as F
import numpy as np 
import pandas as pd 

## 测试网络
1. LSTM 参数测试


In [2]:
lstm=nn.LSTM(128,64,1,0,True)
h0=Parameter(torch.zeros(1),requires_grad=False)
c0=Parameter(torch.zeros(1),requires_grad=False)

In [3]:
x=np.random.random_integers(0,255,(100,3,256))

/var/folders/yc/8mbtdrrx23j2b72x_ykd2t700000gn/T/ipykernel_2664/2923977757.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 255 + 1) instead
  x=np.random.random_integers(0,255,(100,3,256))


In [4]:
x

array([[[ 93, 238, 251, ..., 208, 248, 139],
        [165,  67,  76, ..., 145,  23, 244],
        [152,  14, 115, ..., 154, 109, 168]],

       [[106, 254, 226, ..., 129, 150,  22],
        [  2, 158, 172, ..., 197,  57,  94],
        [ 23, 139,  25, ...,   8, 231,  46]],

       [[ 33, 115, 136, ..., 242, 183, 201],
        [125, 138,  93, ..., 224, 183,  92],
        [227,  82,  85, ..., 190,  25,  11]],

       ...,

       [[ 60, 133, 211, ..., 186, 137, 251],
        [ 43, 104,  20, ...,  54,  52, 151],
        [245,  35, 235, ..., 202, 141, 238]],

       [[147,  48, 232, ..., 105,  28, 182],
        [218, 198,  71, ...,  44,  86,  69],
        [ 59, 118, 106, ...,  71, 248,  93]],

       [[ 55,  57, 203, ...,  57, 218, 100],
        [181,  64,   9, ..., 212, 165, 160],
        [112, 164, 229, ...,   7,   2, 216]]])

In [5]:
conv1d=nn.Conv1d(100,3,256)

In [6]:
ipt=torch.Tensor(x)

In [8]:
conv1d=nn.Conv1d(3,10,20,stride=2)

In [9]:
oup=conv1d(ipt)

In [10]:
oup

tensor([[[  30.3061,   42.8847,  -70.5836,  ...,  -12.0230,   47.2912,
           -28.1074],
         [ -89.4149,  -62.3600, -106.7762,  ...,  -52.3808,  -37.5967,
           -68.8717],
         [ -15.3683,  -94.3784,  -84.6120,  ..., -174.4845,  -70.8106,
           -50.8450],
         ...,
         [ -17.2659,  -10.8455,  -73.5430,  ...,   -4.2622,   26.5225,
            37.5816],
         [ 118.1783,  140.0347,  139.9048,  ...,  219.0810,  194.1817,
           104.4654],
         [  27.8846,   22.7573,   38.0653,  ...,  -34.5330,   30.2121,
           -46.6485]],

        [[  43.1640,  -30.4484,  -29.5112,  ...,   -3.6363,  -94.7283,
            21.7542],
         [ -49.7204,  -33.6140, -127.8033,  ..., -172.9880,  -86.7208,
           -15.5108],
         [-123.2303,  -74.8374,  -76.5510,  ..., -104.3870,  -38.2085,
           -31.8939],
         ...,
         [ 124.5413,   36.6841,   16.5702,  ...,   -9.7331,   -7.3863,
           -12.9283],
         [ 143.5453,  120.0339,  188.020

In [11]:
ipt

tensor([[[ 93., 238., 251.,  ..., 208., 248., 139.],
         [165.,  67.,  76.,  ..., 145.,  23., 244.],
         [152.,  14., 115.,  ..., 154., 109., 168.]],

        [[106., 254., 226.,  ..., 129., 150.,  22.],
         [  2., 158., 172.,  ..., 197.,  57.,  94.],
         [ 23., 139.,  25.,  ...,   8., 231.,  46.]],

        [[ 33., 115., 136.,  ..., 242., 183., 201.],
         [125., 138.,  93.,  ..., 224., 183.,  92.],
         [227.,  82.,  85.,  ..., 190.,  25.,  11.]],

        ...,

        [[ 60., 133., 211.,  ..., 186., 137., 251.],
         [ 43., 104.,  20.,  ...,  54.,  52., 151.],
         [245.,  35., 235.,  ..., 202., 141., 238.]],

        [[147.,  48., 232.,  ..., 105.,  28., 182.],
         [218., 198.,  71.,  ...,  44.,  86.,  69.],
         [ 59., 118., 106.,  ...,  71., 248.,  93.]],

        [[ 55.,  57., 203.,  ...,  57., 218., 100.],
         [181.,  64.,   9.,  ..., 212., 165., 160.],
         [112., 164., 229.,  ...,   7.,   2., 216.]]])

In [12]:
ipt.shape

torch.Size([100, 3, 256])

In [13]:
oup.shape

torch.Size([100, 10, 119])

In [14]:
conv1d.parameters()

<generator object Module.parameters at 0x7faf386d11c0>

In [15]:
p=conv1d.parameters()

In [16]:
for i in p:
    print(i)
    break

Parameter containing:
tensor([[[-2.2311e-02, -9.8607e-02,  9.8273e-02, -1.1522e-02,  3.8090e-02,
           6.5233e-04,  7.4503e-02,  6.9827e-02, -8.8425e-03,  3.2856e-02,
          -1.9535e-02, -1.2516e-01, -7.7030e-02,  2.8599e-02,  1.2802e-01,
          -6.8612e-02, -3.7958e-02, -2.1489e-02,  1.0274e-01, -6.3770e-02],
         [-6.1005e-02,  5.1237e-02, -2.8260e-02,  6.7889e-03,  1.0398e-01,
          -2.8418e-02, -2.9705e-02, -5.0621e-03, -4.2722e-02, -3.6032e-02,
           9.7707e-02, -9.2586e-02, -8.8336e-02, -3.7394e-02, -1.0046e-01,
           1.2275e-01, -1.3188e-02,  4.6747e-02, -6.4009e-02, -3.3469e-02],
         [-4.9413e-02,  1.6825e-02, -9.3766e-02,  6.2993e-02,  1.2828e-01,
           3.7193e-02, -9.8366e-02, -3.3855e-02,  5.8653e-02, -1.0905e-01,
           2.9128e-02,  1.1940e-01, -1.1520e-01,  4.5925e-02, -6.9040e-02,
          -5.1934e-02, -1.2743e-02,  9.1063e-02,  8.7768e-02,  6.5387e-02]],

        [[ 6.9684e-02, -1.9599e-02,  2.8226e-02, -6.0213e-02, -4.1177e-02

In [17]:
c12=nn.Conv1d(3,10,20,dilation=2,padding=10)

In [18]:
o2=c12(ipt)

In [19]:
o2

tensor([[[ 201.0131,  157.4102,  242.5991,  ...,  177.7356,  169.1055,
           122.0209],
         [ -60.2889,  -40.4359,  -50.7647,  ..., -117.9900,  -78.7942,
           -94.4083],
         [  48.7227,  -12.7134,   55.2827,  ...,  -54.7573,   51.7020,
           -10.8936],
         ...,
         [-172.3933,   -4.0872,   -2.8688,  ...,  -11.2667,   -8.2907,
             0.9946],
         [  26.6725,  103.9124,   55.2913,  ...,   20.7143,   41.5786,
            56.1412],
         [ -88.0684,  -76.3163,  -31.6608,  ...,   37.4182,   12.4108,
            71.4153]],

        [[ 173.9916,  177.0352,  167.6745,  ...,  232.1002,  238.6872,
           144.4365],
         [  45.2386,  -68.0512,  -74.2853,  ...,  -67.4101,  -52.2981,
           -88.8001],
         [ -23.4874,  -20.6874,   22.8822,  ...,  -30.4611,   53.7827,
            -7.4454],
         ...,
         [ -89.0203,  -27.7159,  -64.4254,  ...,   75.4617,  -40.0447,
           -81.2051],
         [ 117.6555,  112.7247,   19.030

In [20]:
o2.shape

torch.Size([100, 10, 238])

In [21]:
oup.shape

torch.Size([100, 10, 119])

In [22]:
c12.weight

Parameter containing:
tensor([[[-1.2809e-01,  1.1433e-01,  9.2762e-02,  1.5808e-02, -8.8071e-02,
           1.1542e-01, -3.4233e-02,  6.5949e-02,  1.0911e-01,  8.5094e-02,
          -1.0843e-01, -1.0075e-01,  9.0187e-02,  1.2164e-01,  1.2140e-01,
           7.3187e-02,  1.1482e-01, -8.1862e-02,  1.2424e-01, -1.0636e-01],
         [ 1.1670e-02, -1.1299e-01,  1.2064e-01, -7.9101e-02,  7.1710e-02,
          -3.1613e-03,  1.0264e-01, -7.2200e-02,  5.1377e-02, -6.8654e-03,
           8.2485e-03,  6.3731e-02,  3.5598e-02,  6.7885e-02,  8.7354e-02,
          -1.2814e-02,  1.1780e-02,  6.2081e-02, -3.0692e-02,  1.1271e-01],
         [-1.2433e-01,  1.2620e-01,  1.0214e-01,  1.8273e-02,  5.7019e-02,
           2.3079e-02, -1.0766e-01, -2.0352e-02, -1.9156e-02,  8.8009e-02,
           1.1227e-01,  1.2814e-01,  6.1624e-03,  3.0110e-02,  6.5341e-02,
           9.5449e-02,  7.7940e-02, -1.2110e-01,  1.6311e-02,  1.6309e-03]],

        [[-5.4516e-02, -9.8972e-02,  3.2915e-02,  5.8284e-02,  1.1800e-01

In [23]:
c12.bias.data.shape

torch.Size([10])

In [31]:
d=torch.Tensor([1000,20,3,4,5,6,7,8,9,10])

In [32]:
c12.bias.data=d

In [33]:
c12.bias

Parameter containing:
tensor([1000.,   20.,    3.,    4.,    5.,    6.,    7.,    8.,    9.,   10.],
       requires_grad=True)

In [34]:
o3=c12(ipt)

In [35]:
o3

tensor([[[ 1.2009e+03,  1.1573e+03,  1.2425e+03,  ...,  1.1776e+03,
           1.1690e+03,  1.1219e+03],
         [-4.0318e+01, -2.0465e+01, -3.0793e+01,  ..., -9.8019e+01,
          -5.8823e+01, -7.4437e+01],
         [ 5.1599e+01, -9.8371e+00,  5.8159e+01,  ..., -5.1881e+01,
           5.4578e+01, -8.0173e+00],
         ...,
         [-1.6439e+02,  3.9117e+00,  5.1302e+00,  ..., -3.2677e+00,
          -2.9175e-01,  8.9936e+00],
         [ 3.5759e+01,  1.1300e+02,  6.4378e+01,  ...,  2.9801e+01,
           5.0666e+01,  6.5228e+01],
         [-7.8065e+01, -6.6313e+01, -2.1657e+01,  ...,  4.7422e+01,
           2.2415e+01,  8.1419e+01]],

        [[ 1.1739e+03,  1.1769e+03,  1.1676e+03,  ...,  1.2320e+03,
           1.2386e+03,  1.1443e+03],
         [ 6.5210e+01, -4.8080e+01, -5.4314e+01,  ..., -4.7439e+01,
          -3.2327e+01, -6.8829e+01],
         [-2.0611e+01, -1.7811e+01,  2.5758e+01,  ..., -2.7585e+01,
           5.6659e+01, -4.5691e+00],
         ...,
         [-8.1021e+01, -1

In [30]:
o2

tensor([[[ 201.0131,  157.4102,  242.5991,  ...,  177.7356,  169.1055,
           122.0209],
         [ -60.2889,  -40.4359,  -50.7647,  ..., -117.9900,  -78.7942,
           -94.4083],
         [  48.7227,  -12.7134,   55.2827,  ...,  -54.7573,   51.7020,
           -10.8936],
         ...,
         [-172.3933,   -4.0872,   -2.8688,  ...,  -11.2667,   -8.2907,
             0.9946],
         [  26.6725,  103.9124,   55.2913,  ...,   20.7143,   41.5786,
            56.1412],
         [ -88.0684,  -76.3163,  -31.6608,  ...,   37.4182,   12.4108,
            71.4153]],

        [[ 173.9916,  177.0352,  167.6745,  ...,  232.1002,  238.6872,
           144.4365],
         [  45.2386,  -68.0512,  -74.2853,  ...,  -67.4101,  -52.2981,
           -88.8001],
         [ -23.4874,  -20.6874,   22.8822,  ...,  -30.4611,   53.7827,
            -7.4454],
         ...,
         [ -89.0203,  -27.7159,  -64.4254,  ...,   75.4617,  -40.0447,
           -81.2051],
         [ 117.6555,  112.7247,   19.030